#File: publish.yml
#Authors: Azalea Flynn, Erin Kendall, Jackson Holt 
#   A github action to automatically pull our PR changes down onto the server
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, Icarus-prod]

    steps:
      - uses: actions/checkout@v4

      - name: Upadte site files
        run: |
          cd ../public_html/Icarus
          git fetch origin
          git pull